name: Deploy Training Script to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Authenticate Docker to Google Container Registry
      run: echo "${{ secrets.GCP_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest -f Dockerfile.train .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy training-script \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
