name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy-mlflow-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Validate JSON key
      run: echo "${{ secrets.GCP_CREDENTIALS }}" | jq . > gcp-key.json

    - name: Display JSON key for debugging
      run: |
        echo "JSON key content:"
        cat gcp-key.json
        echo "End of JSON key content"

    - name: Authenticate Docker to Google Container Registry
      run: cat gcp-key.json | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/mlflow-ui:latest -f Dockerfile.mlflow .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/mlflow-ui:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mlflow-ui \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/mlflow-ui:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

  deploy-training-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Grant permissions to service account
      run: |
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT }} \
          --member "serviceAccount:mlops-service-account@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com" \
          --role "roles/aiplatform.user"
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT }} \
          --member "serviceAccount:mlops-service-account@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com" \
          --role "roles/storage.admin"
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT }} \
          --member "serviceAccount:mlops-service-account@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com" \
          --role "roles/aiplatform.admin"

    - name: Validate JSON key
      run: echo "${{ secrets.GCP_CREDENTIALS }}" | jq . > gcp-key.json

    - name: Display JSON key for debugging
      run: |
        echo "JSON key content:"
        cat gcp-key.json
        echo "End of JSON key content"

    - name: Authenticate Docker to Google Container Registry
      run: cat gcp-key.json | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest -f Dockerfile.train .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest

    - name: Create AI Platform Custom Job
      run: |
        gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name=training-script-job \
          --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=gcr.io/${{ secrets.GCP_PROJECT }}/training-script:latest
